### ISSUE TITLE
Response exception on alternating function calls

### ISSUE THREAD

**Issue by timbotimbo** [knrdl/optotron#1]
When trying different functions in sequence, occasionally the response will be detected as invalid even though it seems to be correct.
Here I alternate `get_lamp_hours()` with `set_input_soure()`

I added  `print('raw: ' + txt)`, to see the actual response. 

![optotron](https://user-images.githubusercontent.com/11444698/174076712-8213502f-3453-47a1-a259-dad53b4a247c.jpg)

As a quick fix, calling `flushInput()` before writing to the serial seems to prevent this. So something might be sticking around in the buffer.

**Comment by knrdl** [comment]
Hi, first of all thanks for your feedback ... but I cannot reproduce the problem:
```python
>>> optotron.set_input_source('hdmi'); optotron.get_lamp_hours()
1247
>>> optotron.set_input_source('hdmi'); optotron.get_lamp_hours()
1247
>>> optotron.set_input_source('hdmi'); optotron.get_lamp_hours()
1247
>>> optotron.set_input_source('hdmi'); optotron.get_lamp_hours()
1247
>>> optotron.set_input_source('hdmi'); optotron.get_lamp_hours()
1247
>>> optotron.set_input_source('hdmi'); optotron.get_lamp_hours()
1247
>>> optotron.set_input_source('hdmi'); optotron.get_lamp_hours()
1247
>>> optotron.set_input_source('hdmi'); optotron.get_lamp_hours()
1247
>>> optotron.set_input_source('hdmi'); optotron.get_lamp_hours()
1247
>>> optotron.set_input_source('hdmi'); optotron.get_lamp_hours()
1247
>>> optotron.set_input_source('hdmi'); optotron.get_lamp_hours()
1247
>>> optotron.set_input_source('hdmi'); optotron.get_lamp_hours()
1247
>>> optotron.set_input_source('hdmi'); optotron.get_lamp_hours()
1247
>>> optotron.set_input_source('hdmi')
>>> optotron.set_input_source('hdmi')
>>> optotron.set_input_source('hdmi')
>>> optotron.set_input_source('hdmi')
>>> optotron.set_input_source('hdmi')
>>> optotron.get_lamp_hours()
1247
>>> optotron.get_lamp_hours()
1247
>>> optotron.get_lamp_hours()
1247
>>> optotron.get_lamp_hours()
1247
>>> optotron.get_lamp_hours()
1247
>>> optotron.get_lamp_hours()
1247
>>> optotron.set_input_source('hdmi')
>>> optotron.set_input_source('hdmi')
>>> optotron.set_input_source('hdmi')
```

Anyway flushing buffers sounds like a good thing to do for me :)
If your solution works, please open a PR!

**Comment by timbotimbo** [comment]
Looks like the issue was caused by the cheap usb to serial adapter I used.

I no longer have access to the projector, so I won't make a pull request because I can't do any further testing.
